# Generated by Django 3.0.5 on 2020-04-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werespond', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(null=True, upload_to=None, verbose_name='Event Cover Photo'),
        ),
        migrations.AlterField(
            model_name='eventattendance',
            name='attendance',
            field=models.BooleanField(verbose_name='Attending?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=1, null=True),
        ),
    ]
