# Generated by Django 3.0.4 on 2020-03-18 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werespond', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.CharField(choices=[('c', 'Cardiac Arrest'), ('f', 'Fire Case')], max_length=1, verbose_name='Case Type'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('c', 'Cardiac Arrest'), ('f', 'Fire Report'), ('h', 'Fire Hazard')], max_length=1),
        ),
    ]
